# Generated by Django 4.0.3 on 2022-07-07 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imgUploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='height',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='width',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(height_field='height', upload_to='static', width_field='width'),
            preserve_default=False,
        ),
    ]
