# Generated by Django 4.0.3 on 2022-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUploader', '0002_images_height_images_width_alter_images_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
