# Generated by Django 4.0.3 on 2022-07-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgUploader', '0003_alter_images_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='height',
        ),
        migrations.RemoveField(
            model_name='images',
            name='width',
        ),
    ]
